---
# API Access for the support team
apiVersion: hub.traefik.io/v1alpha1
kind: APIAccess
metadata:
  name: support-team-access
spec:
  groups:
    - support
  apis:
    - name: flight-api # Remove that and add docs why
      namespace: apps # Remove that and add docs why
    - name: ticket-api # Remove that and add docs why
      namespace: apps # Remove that and add docs why
  apiCollections: # Just the collection is enough here!
    - name: demo-travel-collection
---
# API Access for the internal-team
apiVersion: hub.traefik.io/v1alpha1
kind: APIAccess
metadata:
  name: internal-team-access
spec:
  groups:
    - internal
  apis:
    - name: flight-api
      namespace: apps