---
# API Collection containing the Flight and the Ticket API
apiVersion: hub.traefik.io/v1alpha1
kind: APICollection
metadata:
  name: demo-travel-collection
  labels:
    area: travel
spec:
  pathPrefix: "/travel"
  apis:
    - name: flight-api
      namespace: apps
    - name: ticket-api
      namespace: apps