---
# API Portal CRD
apiVersion: hub.traefik.io/v1alpha1
kind: APIPortal
metadata:
  name: traefik-hub-demo-portal
spec:
  title: "Traefik Airlines"
  description: "API Demo Portal"
  apiGateway: traefik-hub-demo-gateway