---
# Ticket API Example
# Ticket API
apiVersion: hub.traefik.io/v1alpha1
kind: API
metadata:
  name: ticket-api
  namespace: apps
  labels:
    area: travel
spec:
  pathPrefix: "/tickets"
  service:
    name: ticket-app
    openApiSpec:
      path: /openapi.yaml
      port:
        number: 3000
    port:
      number: 3000