---
# Flight API Example
# Flight API
apiVersion: hub.traefik.io/v1alpha1
kind: API
metadata:
  name: flight-api
  namespace: apps
  labels:
    area: travel
spec:
  pathPrefix: "/flights"
  service:
    openApiSpec:
      path: /openapi.yaml
      port:
        number: 3000
    name: flight-app
    port:
      number: 3000